### ISSUE TITLE
Timer error

### ISSUE THREAD

**Issue by Nerus87** [kgns/gloves#8] opened 2018-06-30 21:51 UTC
Hi, new error occurred, please fix it:

> L 06/30/2018 - 23:04:44: SourceMod error session started
L 06/30/2018 - 23:04:44: Info (map "de_cache") (file "errors_20180630.log")
L 06/30/2018 - 23:04:44: [SM] Exception reported: Entity 109 (109) is invalid
L 06/30/2018 - 23:04:44: [SM] Blaming: gloves.smx
L 06/30/2018 - 23:04:44: [SM] Call stack trace:
L 06/30/2018 - 23:04:44: [SM]   [0] SetEntPropEnt
L 06/30/2018 - 23:04:44: [SM]   [1] Line 108, gloves/menus.sp::ResetGlovesTimer
L 06/30/2018 - 23:36:30: Error log file session closed.

**Comment by usershtopor** [comment] 2019-01-08 09:02
L 01/07/2019 - 21:19:55: SourceMod error session started
L 01/07/2019 - 21:19:55: Info (map "workshop/172740415/ar_poolstay") (file "errors_20190107.log")
L 01/07/2019 - 21:19:55: [SM] Exception reported: Entity 171 (171) is invalid
L 01/07/2019 - 21:19:55: [SM] Blaming: source_games/gloves.smx
L 01/07/2019 - 21:19:55: [SM] Call stack trace:
L 01/07/2019 - 21:19:55: [SM]   [0] SetEntPropEnt
L 01/07/2019 - 21:19:55: [SM]   [1] Line 108, gloves/menus.sp::ResetGlovesTimer
L 01/07/2019 - 21:44:10: Error log file session closed.

**Comment by kgns** [comment] 2019-01-08 21:44
duplicate of #6

**Closed by kgns** 2019-01-08 21:44 UTC
